### ISSUE TITLE
getting different recommended settings on Y axis 

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [xbst/KUSBA#20]
Hi I have an ender 3 v2 and I'm using this mount for the bed

https://www.printables.com/model/296028-kusba-input-shaper-mount-for-ender-3-and-others

I 'clamps' to the bottom of the bed with a screw.

I find that I am getting different recommended shaper,freq and max_accel when I remount it in the same position ( the same as in the image on printable ) or on the right side. 

I'm making sure the screw is as tight as possible.,

Is this expected?

thanks.

**Comment by xbst** [comment]
I'm not sure how I missed this issue, sorry. LMK if you still need help.

Because you are clamping it on the bed manually, you likely aren't clamping it in the EXACT same position. The slight variation in mounting location can result in slightly different measurements, which can influence the recommended shaper and frequency. This is normal.
